### PR TITLE
feat: bot responds in private chat without reply or mention

### LINKED ISSUE #1: Bot should respond in private chat
Hello, I think it would be nice if the bot responded without being mentioned or replied if the chat is private and not a group.
I'll open a PR, let me know if you find this appropriate.

### PR DESCRIPTION
**Pull request by gianfrancodemarco**
Closes #1

### CODE REVIEW

**Comment by zAlweNy26** [comment]
I agree with your idea, but I would prefer it to be chosen from the .env file, can you do that?
Something like:

ACCESS='PRIVATE|GROUP'

So that it can be chosen to be either accessible in private chat or group, or both.

**Comment by gianfrancodemarco** [comment]
Like this?

- If private -> always reply in private chat, never in groups
- If group -> only reply in groups when mentioned or replied
- If both ->  always reply in private chat, reply in groups when mentioned or replied

**Comment by zAlweNy26** [comment]
@gianfrancodemarco yeah exactly like that, and by default, if the property is missing, it should be only "GROUP"

**Comment by gianfrancodemarco** [comment]
@zAlweNy26 done, let me know what you think about the implementation

**Pull request merged**
